import Link from "next/link";
import { notFound } from "next/navigation";

import { archiveStudent } from "@/actions/student-actions";
import { deleteLesson } from "@/actions/lesson-actions";
import { Button } from "@/components/ui/button";
import { EmptyState, Feedback } from "@/components/ui/feedback";
import { PageHeader } from "@/components/ui/page-header";
import { StatCard } from "@/components/ui/stat-card";
import { StatusBadge } from "@/components/ui/status-badge";
import { formatDate, percent } from "@/lib/format";
import { prisma } from "@/lib/prisma";

export default async function StudentPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string }> }) {
  const [{ id }, { success }] = await Promise.all([params, searchParams]);
  const student = await prisma.student.findUnique({ where: { id }, include: { lessons: { orderBy: [{ lessonDate: "desc" }, { createdAt: "desc" }] } } }); if (!student) notFound();
  const present = student.lessons.filter((l) => l.attendanceStatus === "PRESENT").length; const completed = student.lessons.filter((l) => l.activityCompleted === true).length; const pending = student.lessons.filter((l) => l.activityCompleted === false).length;
  return <div className="page-stack"><PageHeader title={student.name} description={`Cadastro em ${formatDate(student.createdAt)}`} actions={<><Button asChild variant="outline"><Link href={`/alunos/${id}/editar`}>Editar</Link></Button><Button asChild><Link href={`/aulas/nova?studentId=${id}`}>Registrar aula</Link></Button></>} /><Feedback success={success} />
    <div className="flex flex-wrap items-center gap-3 border-y border-[var(--border-subtle)] py-3 text-sm"><StatusBadge tone={student.status === "ACTIVE" ? "green" : "gray"}>{student.status === "ACTIVE" ? "Ativo" : "Inativo"}</StatusBadge><span className="text-zinc-600">{student.email || "Email não informado"}</span><span className="text-zinc-300">•</span><span className="text-zinc-600">{student.phone || "Telefone não informado"}</span>{student.status === "ACTIVE" && <form action={archiveStudent.bind(null, id)} className="ml-auto"><Button type="submit" variant="ghost">Arquivar aluno</Button></form>}</div>
    {student.generalNotes && <div className="border-l-2 border-[var(--border-strong)] px-4 py-2"><p className="text-xs font-medium text-[var(--muted-foreground)]">Observações gerais</p><p className="mt-1 whitespace-pre-wrap text-sm text-zinc-700">{student.generalNotes}</p></div>}
    <section className="metrics-grid"><StatCard label="Total de aulas" value={student.lessons.length} /><StatCard label="Presenças" value={present} /><StatCard label="Faltas" value={student.lessons.length - present} /><StatCard label="Frequência" value={`${percent(present, student.lessons.length)}%`} /><StatCard label="Atividades concluídas" value={completed} /><StatCard label="Atividades pendentes" value={pending} /></section>
    <section><div className="mb-3 flex items-center justify-between"><h2 className="section-heading">Histórico de aulas</h2><Button asChild variant="outline"><Link href={`/relatorios?studentId=${id}`}>Gerar relatório</Link></Button></div>{student.lessons.length === 0 ? <EmptyState title="Nenhuma aula registrada" description="Registre uma aula para iniciar o histórico." /> : <div className="space-y-3">{student.lessons.map((lesson) => <article key={lesson.id} className="flat-card p-4 sm:p-5"><div className="flex flex-wrap items-center gap-2"><time className="font-semibold text-zinc-900">{formatDate(lesson.lessonDate)}</time><StatusBadge tone={lesson.attendanceStatus === "PRESENT" ? "green" : "red"}>{lesson.attendanceStatus === "PRESENT" ? "Presente" : "Falta"}</StatusBadge><StatusBadge tone={lesson.activityCompleted ? "green" : "amber"}>{lesson.activityCompleted ? "Atividade concluída" : "Atividade pendente"}</StatusBadge><div className="ml-auto flex gap-2"><Link href={`/aulas/${lesson.id}/editar`} className="text-xs font-medium text-indigo-700 hover:underline">Editar</Link><form action={deleteLesson.bind(null, lesson.id)}><button type="submit" className="text-xs font-medium text-red-700 hover:underline">Excluir</button></form></div></div><div className="mt-4 grid gap-4 text-sm md:grid-cols-2"><div><p className="text-xs font-medium text-[var(--muted-foreground)]">Conteúdo</p><p className="mt-1 whitespace-pre-wrap text-zinc-700">{lesson.content || "—"}</p></div><div><p className="text-xs font-medium text-[var(--muted-foreground)]">Atividade</p><p className="mt-1 whitespace-pre-wrap text-zinc-700">{lesson.activity || "—"}</p></div>{lesson.notes && <div><p className="text-xs font-medium text-[var(--muted-foreground)]">Observações</p><p className="mt-1 whitespace-pre-wrap text-zinc-700">{lesson.notes}</p></div>}{lesson.nextSteps && <div><p className="text-xs font-medium text-[var(--muted-foreground)]">Próximos passos</p><p className="mt-1 whitespace-pre-wrap text-zinc-700">{lesson.nextSteps}</p></div>}</div></article>)}</div>}</section>
  </div>;
}
