import { completeActivity } from "@/actions/lesson-actions";
import { Button } from "@/components/ui/button";
import { EmptyState, Feedback } from "@/components/ui/feedback";
import { PageHeader } from "@/components/ui/page-header";
import { formatDate } from "@/lib/format";
import { prisma } from "@/lib/prisma";

export default async function PendingPage({ searchParams }: { searchParams: Promise<{ studentId?: string; success?: string }> }) {
  const p = await searchParams;
  const [students, lessons] = await Promise.all([prisma.student.findMany({ orderBy: { name: "asc" }, select: { id: true, name: true } }), prisma.lesson.findMany({ where: { activityCompleted: false, studentId: p.studentId || undefined }, orderBy: { lessonDate: "desc" }, include: { student: { select: { name: true } } } })]);
  return <div className="page-stack"><PageHeader title="Pendências" description="Atividades ainda não concluídas, ligadas ao registro original da aula." /><Feedback success={p.success} /><form className="filter-toolbar grid-cols-[minmax(220px,320px)_auto]"><select name="studentId" defaultValue={p.studentId}><option value="">Todos os alunos</option>{students.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><Button type="submit" variant="outline">Filtrar</Button></form>{lessons.length === 0 ? <EmptyState title="Nenhuma pendência encontrada" description="Todas as atividades selecionadas estão concluídas." /> : <div className="grid gap-3 xl:grid-cols-2">{lessons.map((l) => <article key={l.id} className="flat-card p-5"><div className="flex items-center justify-between gap-4"><h2 className="text-[15px] font-semibold text-[var(--foreground)]">{l.student.name}</h2><span className="shrink-0 text-xs text-[var(--muted-foreground)]">{formatDate(l.lessonDate)}</span></div><dl className="mt-5 space-y-4"><div><dt className="text-xs font-medium text-[var(--muted-foreground)]">Atividade</dt><dd className="mt-1 whitespace-pre-wrap text-sm text-[var(--foreground)]">{l.activity || "Sem descrição"}</dd></div>{l.content && <div><dt className="text-xs font-medium text-[var(--muted-foreground)]">Conteúdo</dt><dd className="mt-1 text-sm text-[var(--foreground)]">{l.content}</dd></div>}{l.notes && <div><dt className="text-xs font-medium text-[var(--muted-foreground)]">Observações</dt><dd className="mt-1 text-sm text-[var(--foreground)]">{l.notes}</dd></div>}{l.nextSteps && <div><dt className="text-xs font-medium text-[var(--muted-foreground)]">Próximos passos</dt><dd className="mt-1 text-sm text-[var(--foreground)]">{l.nextSteps}</dd></div>}</dl><form action={completeActivity.bind(null, l.id)} className="mt-5 border-t border-[var(--border-subtle)] pt-4"><Button type="submit" variant="outline">Marcar como concluída</Button></form></article>)}</div>}</div>;
}
