import { ChevronDown, LogOut } from "lucide-react";

import { logoutAction } from "@/actions/auth-actions";
import { MobileNav } from "@/components/layout/mobile-nav";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";

export function AppHeader({ user }: { user: { id: string; name: string; email: string } }) {
  return <header className="flex h-16 items-center justify-between border-b border-[var(--border)] bg-white px-4 sm:px-6 lg:px-8 xl:px-10"><MobileNav /><div className="hidden lg:block" /><DropdownMenu><DropdownMenuTrigger asChild><button aria-label={`${user.name}, ${user.email}`} className="flex h-9 items-center gap-2 rounded-lg px-2 text-left text-sm text-[var(--muted)] transition-colors duration-150 ease-out hover:bg-[var(--surface-blue-soft)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--primary-light)]"><span className="grid size-7 place-items-center rounded-full border border-[var(--border)] bg-[var(--surface-soft)] text-xs font-semibold text-[var(--foreground)]" aria-hidden="true">{user.name.slice(0, 1).toUpperCase()}</span><span className="hidden sm:block"><span className="block max-w-36 truncate font-medium text-[var(--foreground)]">{user.name}</span></span><ChevronDown aria-hidden="true" size={14} strokeWidth={1.75} /></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel><p className="text-sm font-medium text-[var(--foreground)]">{user.name}</p><p className="text-xs font-normal text-[var(--muted)]">{user.email}</p></DropdownMenuLabel><DropdownMenuSeparator className="my-1 h-px bg-[var(--border-subtle)]" /><DropdownMenuItem disabled>Configurações</DropdownMenuItem><DropdownMenuSeparator className="my-1 h-px bg-[var(--border-subtle)]" /><form action={logoutAction}><DropdownMenuItem asChild><button type="submit" className="w-full"><LogOut aria-hidden="true" size={16} />Sair</button></DropdownMenuItem></form></DropdownMenuContent></DropdownMenu></header>;
}
