import Link from "next/link";
import { notFound } from "next/navigation";

import { Button } from "@/components/ui/button";
import { EmptyState, Feedback } from "@/components/ui/feedback";
import { PageHeader } from "@/components/ui/page-header";
import { StatCard } from "@/components/ui/stat-card";
import { StatusBadge } from "@/components/ui/status-badge";
import { formatDate, percent } from "@/lib/format";
import { prisma } from "@/lib/prisma";

export default async function ClassDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ view?: string; success?: string }> }) {
  const [{ id }, query] = await Promise.all([params, searchParams]);
  const group = await prisma.classGroup.findUnique({ where: { id }, include: { students: { orderBy: { name: "asc" }, include: { lessons: { orderBy: { lessonDate: "desc" } } } } } });
  if (!group) notFound();
  const lessons = group.students.flatMap((student) => student.lessons.map((lesson) => ({ ...lesson, student })));
  const present = lessons.filter((lesson) => lesson.attendanceStatus === "PRESENT").length;
  const view = ["students", "lessons", "reports"].includes(query.view ?? "") ? query.view! : "overview";
  const tabs = [{ id: "overview", label: "Visão geral" }, { id: "students", label: "Alunos" }, { id: "lessons", label: "Aulas" }, { id: "reports", label: "Relatórios" }];
  return <div className="page-stack"><PageHeader title={group.name} description={group.description || "Turma sem descrição."} actions={<><Button asChild variant="outline"><Link href={`/turmas/${id}/editar`}>Editar</Link></Button><Button asChild><Link href={`/aulas/nova/turma?classId=${id}`}>Registrar aula</Link></Button></>} /><Feedback success={query.success} /><nav aria-label="Seções da turma" className="flex gap-1 border-b border-[var(--border)]">{tabs.map((tab) => <Link key={tab.id} href={`/turmas/${id}${tab.id === "overview" ? "" : `?view=${tab.id}`}`} aria-current={view === tab.id ? "page" : undefined} className={`border-b-2 px-3 py-2 text-sm font-medium ${view === tab.id ? "border-[var(--primary)] text-[var(--primary)]" : "border-transparent text-[var(--muted)] hover:text-[var(--foreground)]"}`}>{tab.label}</Link>)}</nav>
    {view === "overview" && <><section className="metrics-grid"><StatCard label="Alunos ativos" value={group.students.filter((student) => student.status === "ACTIVE").length} /><StatCard label="Registros de aula" value={lessons.length} /><StatCard label="Presenças" value={present} /><StatCard label="Faltas" value={lessons.length - present} /><StatCard label="Percentual de presença" value={`${percent(present, lessons.length)}%`} /><StatCard label="Atividades pendentes" value={lessons.filter((lesson) => lesson.activityCompleted === false).length} /></section><section><h2 className="section-heading mb-3">Registros recentes</h2>{lessons.length === 0 ? <EmptyState title="Nenhuma aula registrada" description="Registre uma aula para iniciar o histórico da turma." /> : <div className="table-shell"><table className="data-table"><thead><tr><th>Data</th><th>Aluno</th><th>Presença</th><th>Atividade</th></tr></thead><tbody>{lessons.slice(0, 8).map((lesson) => <tr key={lesson.id}><td>{formatDate(lesson.lessonDate)}</td><td className="primary-cell"><Link href={`/alunos/${lesson.student.id}`}>{lesson.student.name}</Link></td><td><StatusBadge tone={lesson.attendanceStatus === "PRESENT" ? "green" : "red"}>{lesson.attendanceStatus === "PRESENT" ? "Presente" : "Falta"}</StatusBadge></td><td><StatusBadge tone={lesson.activityCompleted ? "green" : "amber"}>{lesson.activityCompleted ? "Concluída" : "Pendente"}</StatusBadge></td></tr>)}</tbody></table></div>}</section></>}
    {view === "students" && (group.students.length === 0 ? <EmptyState title="Esta turma ainda não possui alunos" description="Adicione ou edite um aluno para vinculá-lo a esta turma." /> : <div className="table-shell"><table className="data-table"><thead><tr><th>Aluno</th><th>Aulas</th><th>Presenças</th><th>Faltas</th><th>Frequência</th><th>Pendências</th><th>Status</th></tr></thead><tbody>{group.students.map((student) => { const count = student.lessons.filter((lesson) => lesson.attendanceStatus === "PRESENT").length; return <tr key={student.id}><td className="primary-cell"><Link href={`/alunos/${student.id}`}>{student.name}</Link></td><td>{student.lessons.length}</td><td>{count}</td><td>{student.lessons.length - count}</td><td>{percent(count, student.lessons.length)}%</td><td>{student.lessons.filter((lesson) => lesson.activityCompleted === false).length}</td><td><StatusBadge tone={student.status === "ACTIVE" ? "green" : "gray"}>{student.status === "ACTIVE" ? "Ativo" : "Inativo"}</StatusBadge></td></tr>; })}</tbody></table></div>)}
    {view === "lessons" && <div className="table-shell"><table className="data-table"><thead><tr><th>Data</th><th>Aluno</th><th>Presença</th><th>Conteúdo</th><th>Atividade</th><th>Status</th></tr></thead><tbody>{lessons.map((lesson) => <tr key={lesson.id}><td>{formatDate(lesson.lessonDate)}</td><td>{lesson.student.name}</td><td>{lesson.attendanceStatus === "PRESENT" ? "Presente" : "Falta"}</td><td>{lesson.content || "—"}</td><td>{lesson.activity || "—"}</td><td>{lesson.activityCompleted ? "Concluída" : "Pendente"}</td></tr>)}</tbody></table></div>}
    {view === "reports" && <><section className="metrics-grid"><StatCard label="Total de alunos" value={group.students.length} /><StatCard label="Registros de aula" value={lessons.length} /><StatCard label="Presenças" value={present} /><StatCard label="Faltas" value={lessons.length - present} /><StatCard label="Percentual de presença" value={`${percent(present, lessons.length)}%`} /><StatCard label="Atividades concluídas" value={lessons.filter((lesson) => lesson.activityCompleted === true).length} /><StatCard label="Atividades pendentes" value={lessons.filter((lesson) => lesson.activityCompleted === false).length} /></section><div className="flex gap-2"><Button asChild variant="outline"><Link href={`/relatorios?classId=${id}`}>Abrir relatório com filtros</Link></Button><Button asChild><Link href={`/relatorios/pdf?classId=${id}`} target="_blank">Exportar PDF</Link></Button></div></>}
  </div>;
}
